/**
 * @file Config.h
 * @brief Config Header auto-generated by CMake
 *
 * @author Abhijit Kundu
 */

#ifndef RENDERFOR3DATA_CONFIG_H_
#define RENDERFOR3DATA_CONFIG_H_

/// Absolute Path to the RenderFor3Data root directory
#cmakedefine RENDERFOR3DATA_ROOT_DIR @RENDERFOR3DATA_ROOT_DIR@

#endif // RENDERFOR3DATA_CONFIG_H_

